import 'main.dart';

class RecipeData {
  static List<Recipe> getAllRecipesData() {
    return [
      // CHICKEN DISHES (1-20)
      Recipe(
        id: '1',
        name: 'Chicken Karahi',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Traditional chicken karahi with tomatoes, ginger, and aromatic spices.',
        tags: ['Chicken', 'Karahi', 'Tomatoes', 'Ginger', 'Spices'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '2',
        name: 'Chicken Biryani',
        type: 'Chicken',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Fragrant basmati rice layered with spiced chicken pieces and saffron.',
        tags: ['Chicken', 'Rice', 'Biryani', 'Saffron', 'Aromatic'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '3',
        name: 'Chicken Pulao',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple one-pot chicken and rice dish, perfect for rainy days.',
        tags: ['Chicken', 'Rice', 'One-pot', 'Comfort', 'Simple'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '4',
        name: 'Chicken Qorma',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Rich and creamy chicken curry with yogurt, onions, and aromatic spices.',
        tags: ['Chicken', 'Creamy', 'Yogurt', 'Rich', 'Onions'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '5',
        name: 'Chicken Shorba',
        type: 'Chicken',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Light and healthy chicken soup with ginger and herbs, perfect for cold weather.',
        tags: ['Chicken', 'Soup', 'Healthy', 'Light', 'Ginger'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '6',
        name: 'Chicken Tikka',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Marinated chicken pieces grilled to perfection with traditional spices.',
        tags: ['Chicken', 'Grilled', 'Marinated', 'BBQ', 'Traditional'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '7',
        name: 'Chicken Keema',
        type: 'Chicken',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced minced chicken curry with peas, quick and flavorful.',
        tags: ['Chicken', 'Minced', 'Quick', 'Spicy', 'Peas'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '8',
        name: 'Chicken Pakora',
        type: 'Chicken',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Crispy chicken fritters with gram flour, perfect rainy day snack.',
        tags: ['Chicken', 'Fritters', 'Snack', 'Crispy', 'Gram flour'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '9',
        name: 'Chicken Handi',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Creamy chicken curry cooked in traditional handi with rich gravy.',
        tags: ['Chicken', 'Handi', 'Creamy', 'Rich gravy', 'Traditional'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '10',
        name: 'Chicken Jalfrezi',
        type: 'Chicken',
        time: '45 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Stir-fried chicken with bell peppers, onions, and hot spices.',
        tags: ['Chicken', 'Stir-fried', 'Bell peppers', 'Hot', 'Quick'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '11',
        name: 'Chicken Do Pyaza',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Chicken curry with double onions, aromatic and flavorful.',
        tags: ['Chicken', 'Onions', 'Aromatic', 'Traditional', 'Flavorful'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '12',
        name: 'Chicken Masala',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Classic chicken curry with traditional masala blend.',
        tags: ['Chicken', 'Masala', 'Classic', 'Traditional', 'Curry'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '13',
        name: 'Chicken Bhuna',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Dry chicken curry with thick gravy, perfect with roti.',
        tags: ['Chicken', 'Dry curry', 'Thick gravy', 'Roti companion', 'Spicy'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '14',
        name: 'Chicken Pasanda',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Mild chicken curry with cream and nuts, royal dish.',
        tags: ['Chicken', 'Mild', 'Cream', 'Nuts', 'Royal'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '15',
        name: 'Chicken Korma',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Rich chicken curry with yogurt and cream, mild and creamy.',
        tags: ['Chicken', 'Rich', 'Yogurt', 'Cream', 'Mild'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '16',
        name: 'Chicken Curry',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'All weather',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Basic chicken curry with onions, tomatoes, and spices.',
        tags: ['Chicken', 'Basic', 'Onions', 'Tomatoes', 'Spices'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '17',
        name: 'Chicken Yakhni Pulao',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Rice cooked in chicken broth with whole spices.',
        tags: ['Chicken', 'Rice', 'Broth', 'Whole spices', 'Aromatic'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '18',
        name: 'Chicken Tehri',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced chicken rice with turmeric and aromatic spices.',
        tags: ['Chicken', 'Rice', 'Turmeric', 'Spiced', 'Aromatic'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '19',
        name: 'Chicken Zarda',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Sweet chicken rice with nuts and dried fruits.',
        tags: ['Chicken', 'Rice', 'Sweet', 'Nuts', 'Dried fruits'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '20',
        name: 'Chicken Shami Kabab',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Soft chicken kababs with lentils and aromatic spices.',
        tags: ['Chicken', 'Kabab', 'Lentils', 'Soft', 'Aromatic'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),

      // MUTTON/BEEF DISHES (21-50)
      Recipe(
        id: '21',
        name: 'Aloo Gosht',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Traditional potato and meat curry, comfort food at its best.',
        tags: ['Mutton', 'Potato', 'Traditional', 'Comfort', 'Curry'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '22',
        name: 'Mutton Biryani',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Royal mutton biryani with aromatic spices, saffron, and caramelized onions.',
        tags: ['Mutton', 'Rice', 'Biryani', 'Royal', 'Saffron'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '23',
        name: 'Mutton Karahi',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Traditional mutton cooked in karahi with tomatoes and ginger.',
        tags: ['Mutton', 'Karahi', 'Traditional', 'Spicy', 'Tomatoes'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '24',
        name: 'Beef Nihari',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Slow-cooked beef stew with wheat flour, perfect for cold mornings.',
        tags: ['Beef', 'Slow-cooked', 'Rich', 'Traditional', 'Wheat flour'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '25',
        name: 'Beef Qeema',
        type: 'Mutton/Beef',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced minced beef curry with potatoes, quick and satisfying.',
        tags: ['Beef', 'Minced', 'Quick', 'Spiced', 'Potatoes'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '26',
        name: 'Mutton Yakhni Pulao',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Low energy',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Fragrant rice cooked in mutton broth with whole spices.',
        tags: ['Mutton', 'Rice', 'Broth', 'Aromatic', 'Whole spices'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '27',
        name: 'Seekh Kabab',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Grilled minced meat skewers with aromatic spices and onions.',
        tags: ['Kabab', 'Grilled', 'Minced', 'Skewers', 'Onions'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '28',
        name: 'BBQ Tikka Boti',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Grilled meat chunks with traditional spices and yogurt marinade.',
        tags: ['BBQ', 'Grilled', 'Chunks', 'Spicy', 'Yogurt'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '29',
        name: 'Mutton Curry',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Traditional mutton curry with onions, tomatoes, and spices.',
        tags: ['Mutton', 'Curry', 'Traditional', 'Onions', 'Tomatoes'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '30',
        name: 'Beef Curry',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Rich beef curry with traditional spices and gravy.',
        tags: ['Beef', 'Curry', 'Rich', 'Traditional', 'Gravy'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '31',
        name: 'Mutton Bhuna',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Dry mutton curry with thick gravy, perfect with roti.',
        tags: ['Mutton', 'Dry curry', 'Thick gravy', 'Roti companion', 'Spicy'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '32',
        name: 'Beef Bhuna',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Dry beef curry with thick gravy, rich and flavorful.',
        tags: ['Beef', 'Dry curry', 'Thick gravy', 'Rich', 'Flavorful'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '33',
        name: 'Mutton Qorma',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Rich mutton curry with yogurt, cream, and aromatic spices.',
        tags: ['Mutton', 'Rich', 'Yogurt', 'Cream', 'Aromatic'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '34',
        name: 'Beef Qorma',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Rich beef curry with yogurt, cream, and aromatic spices.',
        tags: ['Beef', 'Rich', 'Yogurt', 'Cream', 'Aromatic'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '35',
        name: 'Mutton Handi',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Creamy mutton curry cooked in traditional handi.',
        tags: ['Mutton', 'Handi', 'Creamy', 'Traditional', 'Rich'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '36',
        name: 'Beef Handi',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Creamy beef curry cooked in traditional handi.',
        tags: ['Beef', 'Handi', 'Creamy', 'Traditional', 'Rich'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '37',
        name: 'Mutton Jalfrezi',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Stir-fried mutton with bell peppers and hot spices.',
        tags: ['Mutton', 'Stir-fried', 'Bell peppers', 'Hot', 'Spicy'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '38',
        name: 'Beef Jalfrezi',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Stir-fried beef with bell peppers and hot spices.',
        tags: ['Beef', 'Stir-fried', 'Bell peppers', 'Hot', 'Spicy'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '39',
        name: 'Mutton Do Pyaza',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Mutton curry with double onions, aromatic and flavorful.',
        tags: ['Mutton', 'Onions', 'Aromatic', 'Traditional', 'Flavorful'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '40',
        name: 'Beef Do Pyaza',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Beef curry with double onions, aromatic and flavorful.',
        tags: ['Beef', 'Onions', 'Aromatic', 'Traditional', 'Flavorful'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '41',
        name: 'Mutton Masala',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Classic mutton curry with traditional masala blend.',
        tags: ['Mutton', 'Masala', 'Classic', 'Traditional', 'Curry'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '42',
        name: 'Beef Masala',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Classic beef curry with traditional masala blend.',
        tags: ['Beef', 'Masala', 'Classic', 'Traditional', 'Curry'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '43',
        name: 'Mutton Pasanda',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Mild mutton curry with cream and nuts, royal dish.',
        tags: ['Mutton', 'Mild', 'Cream', 'Nuts', 'Royal'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '44',
        name: 'Beef Pasanda',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Mild beef curry with cream and nuts, royal dish.',
        tags: ['Beef', 'Mild', 'Cream', 'Nuts', 'Royal'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '45',
        name: 'Mutton Korma',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Rich mutton curry with yogurt and cream, mild and creamy.',
        tags: ['Mutton', 'Rich', 'Yogurt', 'Cream', 'Mild'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '46',
        name: 'Beef Korma',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Rich beef curry with yogurt and cream, mild and creamy.',
        tags: ['Beef', 'Rich', 'Yogurt', 'Cream', 'Mild'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '47',
        name: 'Mutton Pulao',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'One-pot mutton and rice with aromatic spices.',
        tags: ['Mutton', 'Rice', 'One-pot', 'Aromatic', 'Comfort'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '48',
        name: 'Beef Pulao',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'One-pot beef and rice with aromatic spices.',
        tags: ['Beef', 'Rice', 'One-pot', 'Aromatic', 'Comfort'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '49',
        name: 'Mutton Tehri',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced mutton rice with turmeric and aromatic spices.',
        tags: ['Mutton', 'Rice', 'Turmeric', 'Spiced', 'Aromatic'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),
      Recipe(
        id: '50',
        name: 'Beef Tehri',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced beef rice with turmeric and aromatic spices.',
        tags: ['Beef', 'Rice', 'Turmeric', 'Spiced', 'Aromatic'],
        imageUrl: 'https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2023/04/IMG_9109.jpg?resize=1200%2C1500&ssl=1',
      ),

      // Continue with more recipes...
      // This is just the beginning - I'll continue with the remaining 150+ recipes
    ];
  }
}