// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3yP6pp5Dr3UujdOH3YqNcnWyOztXNPIA',
    appId: '1:386398056797:web:72c5c43534567b7538f8b4',
    messagingSenderId: '386398056797',
    projectId: 'ajkyapakaein',
    authDomain: 'ajkyapakaein.firebaseapp.com',
    storageBucket: 'ajkyapakaein.firebasestorage.app',
    measurementId: 'G-JK5J77H2BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5j0SUd3KtooQQAl3W1YrsMk_xSVGw8Ow',
    appId: '1:386398056797:android:ab520a4ffe34b15b38f8b4',
    messagingSenderId: '386398056797',
    projectId: 'ajkyapakaein',
    storageBucket: 'ajkyapakaein.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSvjqn8_YQJhss4O7h9s-xB1wA2gAa5L0',
    appId: '1:386398056797:ios:7c4a4354fd3c93a838f8b4',
    messagingSenderId: '386398056797',
    projectId: 'ajkyapakaein',
    storageBucket: 'ajkyapakaein.firebasestorage.app',
    iosBundleId: 'com.example.ajKyapakaein',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSvjqn8_YQJhss4O7h9s-xB1wA2gAa5L0',
    appId: '1:386398056797:ios:7c4a4354fd3c93a838f8b4',
    messagingSenderId: '386398056797',
    projectId: 'ajkyapakaein',
    storageBucket: 'ajkyapakaein.firebasestorage.app',
    iosBundleId: 'com.example.ajKyapakaein',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3yP6pp5Dr3UujdOH3YqNcnWyOztXNPIA',
    appId: '1:386398056797:web:e8b523a04e89802338f8b4',
    messagingSenderId: '386398056797',
    projectId: 'ajkyapakaein',
    authDomain: 'ajkyapakaein.firebaseapp.com',
    storageBucket: 'ajkyapakaein.firebasestorage.app',
    measurementId: 'G-69PDGLMHT4',
  );
}
