
import 'main.dart';

class RecipeData {
  static List<Recipe> getAllRecipesData() {
    return [
      // CHICKEN DISHES (Enhanced)
      Recipe(
        id: '1',
        name: 'Chicken Curry (Karahi style)',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Traditional chicken karahi with tomatoes and aromatic spices.',
        tags: ['Chicken', 'Karahi', 'Tomatoes', 'Spices', 'Winter', 'Warm'],
        imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
      ),
      Recipe(
        id: '2',
        name: 'Chicken Biryani',
        type: 'Chicken',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal', // Available year-round
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Fragrant basmati rice layered with spiced chicken pieces.',
        tags: ['Chicken', 'Rice', 'Biryani', 'Saffron', 'Festive', 'Popular'],
        imageUrl: 'https://images.unsplash.com/photo-1563379091339-03246963d51a?w=400',
      ),
      Recipe(
        id: '3',
        name: 'Chicken Pulao',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal', // Good for any weather
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple one-pot chicken and rice dish, perfect comfort food.',
        tags: ['Chicken', 'Rice', 'One-pot', 'Comfort', 'Easy'],
        imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
      ),
      Recipe(
        id: '4',
        name: 'Chicken Qorma',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Rich and creamy chicken curry with yogurt and spices.',
        tags: ['Chicken', 'Creamy', 'Yogurt', 'Rich'],
        imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400',
      ),
      Recipe(
        id: '5',
        name: 'Chicken Shorba',
        type: 'Chicken',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Light and healthy chicken soup, perfect for cold weather.',
        tags: ['Chicken', 'Soup', 'Healthy', 'Light'],
        imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
      ),
      Recipe(
        id: '6',
        name: 'Chicken Tikka',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Marinated chicken pieces grilled to perfection.',
        tags: ['Chicken', 'Grilled', 'Marinated', 'BBQ'],
        imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
      ),
      Recipe(
        id: '7',
        name: 'Chicken Keema',
        type: 'Chicken',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced minced chicken curry, quick and flavorful.',
        tags: ['Chicken', 'Minced', 'Quick', 'Spicy'],
        imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400',
      ),
      Recipe(
        id: '8',
        name: 'Chicken Pakora',
        type: 'Chicken',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Crispy chicken fritters, perfect rainy day snack.',
        tags: ['Chicken', 'Fritters', 'Snack', 'Crispy'],
        imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
      ),
      Recipe(
        id: '9',
        name: 'Chicken Jalfrezi',
        type: 'Chicken',
        time: '30-35 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Stir-fried chicken with colorful bell peppers and onions.',
        tags: ['Chicken', 'Stir-fry', 'Bell peppers', 'Quick'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),
      Recipe(
        id: '10',
        name: 'Chicken Handi',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Rich chicken curry cooked in traditional clay pot style.',
        tags: ['Chicken', 'Rich', 'Traditional', 'Clay pot'],
        imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400',
      ),

      // VEGETABLE DISHES (Enhanced & Expanded)
      Recipe(
        id: '11',
        name: 'Aloo Palak',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Nutritious potato and spinach curry.',
        tags: ['Potato', 'Spinach', 'Healthy', 'Vegetarian'],
        imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400',
      ),
      Recipe(
        id: '12',
        name: 'Aloo Matar',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple potato and peas curry, comfort food at its best.',
        tags: ['Potato', 'Peas', 'Simple', 'Comfort'],
        imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      ),
      Recipe(
        id: '13',
        name: 'Aloo Gobi',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Traditional potato and cauliflower curry with turmeric.',
        tags: ['Potato', 'Cauliflower', 'Traditional', 'Turmeric'],
        imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400',
      ),
      Recipe(
        id: '14',
        name: 'Bhindi Masala',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced okra curry, perfect for hot weather.',
        tags: ['Okra', 'Spices', 'Quick', 'Summer'],
        imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400',
      ),
      Recipe(
        id: '15',
        name: 'Palak Paneer',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Creamy spinach curry with cottage cheese.',
        tags: ['Spinach', 'Paneer', 'Creamy', 'Protein'],
        imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400',
      ),
      Recipe(
        id: '16',
        name: 'Mixed Sabzi',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Healthy mix of seasonal vegetables.',
        tags: ['Mixed', 'Healthy', 'Seasonal', 'Light'],
        imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400',
      ),
      Recipe(
        id: '17',
        name: 'Baingan Bhartha',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Smoky roasted eggplant curry, summer favorite.',
        tags: ['Eggplant', 'Smoky', 'Roasted', 'Summer'],
        imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400',
      ),
      Recipe(
        id: '18',
        name: 'Tinda Masala',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Apple gourd curry, popular summer vegetable.',
        tags: ['Tinda', 'Summer', 'Gourd', 'Traditional'],
        imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400',
      ),
      Recipe(
        id: '19',
        name: 'Arvi Masala',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced taro root curry, traditional vegetable dish.',
        tags: ['Taro', 'Root vegetable', 'Traditional', 'Spiced'],
        imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400',
      ),
      Recipe(
        id: '20',
        name: 'Karela Masala',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Bitter gourd curry, healthy and nutritious.',
        tags: ['Bitter gourd', 'Healthy', 'Nutritious', 'Summer'],
        imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400',
      ),

      // MUTTON/BEEF DISHES (Enhanced & Expanded)
      Recipe(
        id: '21',
        name: 'Mutton Biryani',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Royal mutton biryani with aromatic spices and saffron.',
        tags: ['Mutton', 'Rice', 'Biryani', 'Royal'],
        imageUrl: 'https://images.unsplash.com/photo-1563379091339-03246963d51a?w=400',
      ),
      Recipe(
        id: '22',
        name: 'Mutton Karahi',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Traditional mutton cooked in karahi with tomatoes.',
        tags: ['Mutton', 'Karahi', 'Traditional', 'Spicy'],
        imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
      ),
      Recipe(
        id: '23',
        name: 'Beef Nihari',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Slow-cooked beef stew, perfect for cold mornings.',
        tags: ['Beef', 'Slow-cooked', 'Rich', 'Traditional'],
        imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400',
      ),
      Recipe(
        id: '24',
        name: 'Beef Qeema',
        type: 'Mutton/Beef',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced minced beef curry, quick and satisfying.',
        tags: ['Beef', 'Minced', 'Quick', 'Spiced'],
        imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400',
      ),
      Recipe(
        id: '25',
        name: 'Mutton Yakhni Pulao',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Low energy',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Fragrant rice cooked in mutton broth.',
        tags: ['Mutton', 'Rice', 'Broth', 'Aromatic'],
        imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
      ),
      Recipe(
        id: '26',
        name: 'Chapli Kebab',
        type: 'Mutton/Beef',
        time: '30-35 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Famous Peshawari flat kebabs with herbs and spices.',
        tags: ['Kebab', 'Peshawari', 'Herbs', 'Flat'],
        imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
      ),
      Recipe(
        id: '27',
        name: 'Shami Kebab',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Soft lentil and meat patties, perfect appetizer.',
        tags: ['Kebab', 'Lentils', 'Soft', 'Appetizer'],
        imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
      ),
      Recipe(
        id: '28',
        name: 'Beef Kofta',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced meatballs in rich curry sauce.',
        tags: ['Meatballs', 'Curry', 'Rich', 'Spiced'],
        imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400',
      ),
      Recipe(
        id: '29',
        name: 'Mutton Pasanda',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Tender mutton slices in creamy yogurt curry.',
        tags: ['Mutton', 'Tender', 'Creamy', 'Yogurt'],
        imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400',
      ),

      // FISH/SEAFOOD DISHES (Enhanced & Expanded)
      Recipe(
        id: '30',
        name: 'Fish Curry',
        type: 'Fish/SeaFood',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal', // Available in multiple seasons
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Traditional fish curry with aromatic spices.',
        tags: ['Fish', 'Curry', 'Spices', 'Traditional', 'Protein'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),
      Recipe(
        id: '31',
        name: 'Fish Biryani',
        type: 'Fish/SeaFood',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal', // Available year-round
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Aromatic fish biryani with basmati rice.',
        tags: ['Fish', 'Rice', 'Biryani', 'Aromatic', 'Special'],
        imageUrl: 'https://images.unsplash.com/photo-1563379091339-03246963d51a?w=400',
      ),
      Recipe(
        id: '32',
        name: 'Fried Fish Masala',
        type: 'Fish/SeaFood',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Hot', // Good for hot weather
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Crispy fried fish with spicy masala coating.',
        tags: ['Fish', 'Fried', 'Crispy', 'Spicy', 'Summer'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),
      Recipe(
        id: '33',
        name: 'Prawn Curry',
        type: 'Fish/SeaFood',
        time: '30-35 minutes',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Rich and spicy prawn curry with coconut.',
        tags: ['Prawns', 'Curry', 'Coconut', 'Rich'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),
      Recipe(
        id: '34',
        name: 'Fish Tikka',
        type: 'Fish/SeaFood',
        time: '30-35 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Marinated fish pieces grilled with spices.',
        tags: ['Fish', 'Grilled', 'Marinated', 'Spices'],
        imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
      ),

      // LENTILS & DAILY ITEMS (Enhanced & Expanded)
      Recipe(
        id: '35',
        name: 'Dal Chawal',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple lentils with rice, ultimate comfort food.',
        tags: ['Lentils', 'Rice', 'Comfort', 'Simple'],
        imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      ),
      Recipe(
        id: '36',
        name: 'Chana Dal',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Nutritious split chickpea curry.',
        tags: ['Chickpeas', 'Nutritious', 'Protein', 'Healthy'],
        imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      ),
      Recipe(
        id: '37',
        name: 'Khichdi',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Comfort food made with rice and lentils.',
        tags: ['Rice', 'Lentils', 'Comfort', 'Sick-day food'],
        imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      ),
      Recipe(
        id: '38',
        name: 'Masoor Dal',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Quick cooking red lentils, protein rich.',
        tags: ['Red lentils', 'Quick', 'Protein', 'Easy'],
        imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      ),
      Recipe(
        id: '39',
        name: 'Moong Dal',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Light yellow lentils, easy to digest.',
        tags: ['Yellow lentils', 'Light', 'Digestible', 'Healthy'],
        imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      ),
      Recipe(
        id: '40',
        name: 'Mixed Dal',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Combination of different lentils for variety.',
        tags: ['Mixed lentils', 'Variety', 'Nutritious', 'Protein'],
        imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      ),

      // SNACKS & FRITTERS (Enhanced & Expanded)
      Recipe(
        id: '41',
        name: 'Pakoray',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Crispy vegetable fritters, perfect for rainy weather.',
        tags: ['Fritters', 'Crispy', 'Rainy-day', 'Snack'],
        imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
      ),
      Recipe(
        id: '42',
        name: 'Aloo Pakora',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Crispy potato fritters, monsoon favorite.',
        tags: ['Potato', 'Fritters', 'Monsoon', 'Crispy'],
        imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
      ),
      Recipe(
        id: '43',
        name: 'Pyaz Pakora',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Onion fritters, perfect tea-time snack.',
        tags: ['Onion', 'Fritters', 'Tea-time', 'Snack'],
        imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
      ),
      Recipe(
        id: '44',
        name: 'Samosa',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Active',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Crispy triangular pastry with spiced potato filling.',
        tags: ['Pastry', 'Potato', 'Crispy', 'Traditional'],
        imageUrl: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa7e38?w=400',
      ),

      // EGG DISHES (Enhanced & Expanded)
      Recipe(
        id: '45',
        name: 'Anda Curry',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Low energy',
        budget: 'Very low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced egg curry, quick and protein-rich.',
        tags: ['Eggs', 'Curry', 'Protein', 'Quick'],
        imageUrl: 'https://images.unsplash.com/photo-1582169296194-e4d644b24fbe?w=400',
      ),
      Recipe(
        id: '46',
        name: 'Anda Paratha',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Egg-stuffed flatbread, perfect breakfast option.',
        tags: ['Eggs', 'Paratha', 'Breakfast', 'Filling'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),
      Recipe(
        id: '47',
        name: 'Bhurji',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Scrambled eggs with onions and spices.',
        tags: ['Scrambled eggs', 'Onions', 'Quick', 'Breakfast'],
        imageUrl: 'https://images.unsplash.com/photo-1582169296194-e4d644b24fbe?w=400',
      ),
      Recipe(
        id: '48',
        name: 'Boiled Egg Masala',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Hard-boiled eggs in spicy tomato curry.',
        tags: ['Boiled eggs', 'Tomato', 'Spicy', 'Curry'],
        imageUrl: 'https://images.unsplash.com/photo-1582169296194-e4d644b24fbe?w=400',
      ),

      // BREAD & RICE DISHES (New Category)
      Recipe(
        id: '49',
        name: 'Sindhi Biryani',
        type: 'Vegetables',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Tangy and colorful vegetable biryani with potatoes and plums.',
        tags: ['Rice', 'Vegetables', 'Tangy', 'Colorful'],
        imageUrl: 'https://images.unsplash.com/photo-1563379091339-03246963d51a?w=400',
      ),
      Recipe(
        id: '50',
        name: 'Plain Pulao',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple aromatic rice dish with whole spices.',
        tags: ['Rice', 'Simple', 'Aromatic', 'Spices'],
        imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
      ),
      Recipe(
        id: '51',
        name: 'Zarda',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Sweet saffron rice with nuts and raisins.',
        tags: ['Sweet rice', 'Saffron', 'Nuts', 'Festive'],
        imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
      ),
      Recipe(
        id: '52',
        name: 'Naan',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Active',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Soft leavened flatbread baked in tandoor.',
        tags: ['Bread', 'Tandoor', 'Soft', 'Leavened'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),
      Recipe(
        id: '53',
        name: 'Roti',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple whole wheat flatbread, daily staple.',
        tags: ['Bread', 'Wheat', 'Daily', 'Simple'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),
      Recipe(
        id: '54',
        name: 'Paratha',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Layered flatbread with ghee, breakfast favorite.',
        tags: ['Bread', 'Layered', 'Ghee', 'Breakfast'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),

      // SPECIAL/FESTIVE DISHES (Enhanced & Expanded)
      Recipe(
        id: '55',
        name: 'Paye',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Traditional slow-cooked trotters, winter special.',
        tags: ['Trotters', 'Slow-cooked', 'Traditional', 'Winter'],
        imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400',
      ),
      Recipe(
        id: '56',
        name: 'Sajji',
        type: 'Chicken',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Whole roasted chicken/mutton, perfect for gatherings.',
        tags: ['Roasted', 'Whole', 'Festive', 'Gathering'],
        imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
      ),
      Recipe(
        id: '57',
        name: 'BBQ Tikka Boti',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Grilled meat chunks with traditional spices.',
        tags: ['BBQ', 'Grilled', 'Chunks', 'Spicy'],
        imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
      ),
      Recipe(
        id: '58',
        name: 'Seekh Kabab',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Grilled minced meat skewers with aromatic spices.',
        tags: ['Kabab', 'Grilled', 'Minced', 'Skewers'],
        imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
      ),
      Recipe(
        id: '59',
        name: 'Haleem',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Rich lentil and meat stew, Ramadan special.',
        tags: ['Lentils', 'Meat', 'Rich', 'Ramadan'],
        imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400',
      ),
      Recipe(
        id: '60',
        name: 'Karhi Pakora',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Yogurt-based curry with crispy fritters.',
        tags: ['Yogurt', 'Fritters', 'Tangy', 'Rainy-weather'],
        imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400',
      ),

      // BREAKFAST ITEMS (New Category)
      Recipe(
        id: '61',
        name: 'Halwa Puri',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Traditional breakfast with semolina halwa and fried bread.',
        tags: ['Breakfast', 'Halwa', 'Puri', 'Traditional'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),
      Recipe(
        id: '62',
        name: 'Channay',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced chickpeas curry, breakfast staple.',
        tags: ['Chickpeas', 'Breakfast', 'Spiced', 'Curry'],
        imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      ),
      Recipe(
        id: '63',
        name: 'Aloo Paratha',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Potato-stuffed flatbread, hearty breakfast.',
        tags: ['Potato', 'Stuffed', 'Breakfast', 'Hearty'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),
      Recipe(
        id: '64',
        name: 'Keema Paratha',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Minced meat stuffed flatbread, protein-rich breakfast.',
        tags: ['Minced meat', 'Stuffed', 'Protein', 'Breakfast'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),

      // DESSERTS (New Category)
      Recipe(
        id: '65',
        name: 'Kheer',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Creamy rice pudding with milk and cardamom.',
        tags: ['Dessert', 'Rice pudding', 'Creamy', 'Sweet'],
        imageUrl: 'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400',
      ),
      Recipe(
        id: '66',
        name: 'Gajar Halwa',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Sweet carrot pudding, winter dessert favorite.',
        tags: ['Dessert', 'Carrot', 'Sweet', 'Winter'],
        imageUrl: 'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400',
      ),
      Recipe(
        id: '67',
        name: 'Gulab Jamun',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Deep-fried milk balls in sugar syrup.',
        tags: ['Dessert', 'Fried', 'Sweet', 'Syrup'],
        imageUrl: 'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=400',
      ),

      // REGIONAL SPECIALTIES (New Category)
      Recipe(
        id: '68',
        name: 'Peshawari Karahi',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Famous Peshawar-style mutton karahi with minimal spices.',
        tags: ['Peshawari', 'Regional', 'Minimal spices', 'Famous'],
        imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
      ),
      Recipe(
        id: '69',
        name: 'Lahori Chargha',
        type: 'Chicken',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Lahore-style whole roasted chicken with special marinade.',
        tags: ['Lahori', 'Whole chicken', 'Roasted', 'Special'],
        imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
      ),
      Recipe(
        id: '70',
        name: 'Karachi Biryani',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Karachi-style spicy biryani with potatoes and boiled eggs.',
        tags: ['Karachi', 'Spicy', 'Potatoes', 'Eggs'],
        imageUrl: 'https://images.unsplash.com/photo-1563379091339-03246963d51a?w=400',
      ),

      // SUMMER SPECIALTIES
      Recipe(
        id: '71',
        name: 'Kachumber Salad',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Fresh cucumber and tomato salad, perfect for hot weather.',
        tags: ['Salad', 'Fresh', 'Cucumber', 'Summer'],
        imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400',
      ),
      Recipe(
        id: '72',
        name: 'Raita',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Cooling yogurt side dish with cucumber or mint.',
        tags: ['Yogurt', 'Cooling', 'Side dish', 'Mint'],
        imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400',
      ),

      // WINTER SPECIALTIES
      Recipe(
        id: '73',
        name: 'Saag',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Mixed greens curry, winter specialty with mustard leaves.',
        tags: ['Greens', 'Winter', 'Mustard leaves', 'Healthy'],
        imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400',
      ),
      Recipe(
        id: '74',
        name: 'Makki Ki Roti Sarson Ka Saag',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Active',
        budget: 'Low budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Corn flatbread with mustard greens, winter classic.',
        tags: ['Corn bread', 'Mustard greens', 'Winter', 'Classic'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),

      // QUICK FIXES & INSTANT MEALS
      Recipe(
        id: '75',
        name: 'Maggi/Instant Noodles',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Quick instant noodles with vegetables, student favorite.',
        tags: ['Instant', 'Quick', 'Noodles', 'Student food'],
        imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400',
      ),
      Recipe(
        id: '76',
        name: 'Bread Omelet',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Quick bread and egg combination, instant meal.',
        tags: ['Bread', 'Eggs', 'Quick', 'Instant'],
        imageUrl: 'https://images.unsplash.com/photo-1582169296194-e4d644b24fbe?w=400',
      ),

      // STREET FOOD FAVORITES
      Recipe(
        id: '77',
        name: 'Gol Gappay/Pani Puri',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Active',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Crispy shells with spiced water, popular street food.',
        tags: ['Street food', 'Crispy', 'Spiced water', 'Popular'],
        imageUrl: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa7e38?w=400',
      ),
      Recipe(
        id: '78',
        name: 'Chaat',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Mixed savory snack with chutneys and spices.',
        tags: ['Chaat', 'Savory', 'Chutneys', 'Mixed'],
        imageUrl: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa7e38?w=400',
      ),
      Recipe(
        id: '79',
        name: 'Bun Kebab',
        type: 'Mutton/Beef',
        time: '30-35 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Pakistani burger with shami kebab and chutneys.',
        tags: ['Burger', 'Shami kebab', 'Chutneys', 'Pakistani'],
        imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
      ),

      // BEVERAGES & DRINKS
      Recipe(
        id: '80',
        name: 'Chai/Tea',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Traditional milk tea with cardamom and sugar.',
        tags: ['Tea', 'Milk', 'Cardamom', 'Traditional'],
        imageUrl: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400',
      ),
      Recipe(
        id: '81',
        name: 'Lassi',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Refreshing yogurt drink, perfect for summer.',
        tags: ['Yogurt drink', 'Refreshing', 'Summer', 'Cool'],
        imageUrl: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400',
      ),

      // ADDITIONAL POPULAR DISHES
      Recipe(
        id: '82',
        name: 'Chicken Manchurian',
        type: 'Chicken',
        time: '30-35 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Indo-Chinese fusion chicken in tangy sauce.',
        tags: ['Fusion', 'Tangy', 'Indo-Chinese', 'Sauce'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),
      Recipe(
        id: '83',
        name: 'Chicken Corn Soup',
        type: 'Chicken',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Thick soup with chicken and sweet corn.',
        tags: ['Soup', 'Thick', 'Sweet corn', 'Warm'],
        imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
      ),
      Recipe(
        id: '84',
        name: 'Mutton Stew',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Slow-cooked mutton with vegetables in rich gravy.',
        tags: ['Slow-cooked', 'Vegetables', 'Rich gravy', 'Tender'],
        imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400',
      ),
      Recipe(
        id: '85',
        name: 'Fish Pakora',
        type: 'Fish/SeaFood',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Crispy fish fritters, perfect for monsoon.',
        tags: ['Fish', 'Fritters', 'Crispy', 'Monsoon'],
        imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
      ),
      Recipe(
        id: '86',
        name: 'Daal Makhani',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Creamy black lentils with butter and cream.',
        tags: ['Black lentils', 'Creamy', 'Butter', 'Rich'],
        imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
      ),
      Recipe(
        id: '87',
        name: 'Chicken Cheese Karahi',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Modern chicken karahi with melted cheese.',
        tags: ['Modern', 'Cheese', 'Melted', 'Fusion'],
        imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
      ),
      Recipe(
        id: '88',
        name: 'Beef Pulao',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Aromatic rice with tender beef pieces.',
        tags: ['Rice', 'Tender beef', 'Aromatic', 'One-pot'],
        imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
      ),
      Recipe(
        id: '89',
        name: 'Vegetable Biryani',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Fragrant rice with mixed vegetables and aromatic spices.',
        tags: ['Vegetarian', 'Mixed vegetables', 'Fragrant', 'Spices'],
        imageUrl: 'https://images.unsplash.com/photo-1563379091339-03246963d51a?w=400',
      ),
      Recipe(
        id: '90',
        name: 'Chicken White Karahi',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Creamy white chicken karahi without tomatoes.',
        tags: ['Creamy', 'White', 'No tomatoes', 'Mild'],
        imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
      ),
      Recipe(
        id: '91',
        name: 'Mutton Chops',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Grilled mutton chops with spicy marinade.',
        tags: ['Grilled', 'Chops', 'Spicy marinade', 'BBQ'],
        imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
      ),
      Recipe(
        id: '92',
        name: 'Chicken Rolls',
        type: 'Chicken',
        time: '30-35 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Chicken tikka wrapped in paratha with salad.',
        tags: ['Wrapped', 'Tikka', 'Paratha', 'Salad'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),
      Recipe(
        id: '93',
        name: 'Fish Fingers',
        type: 'Fish/SeaFood',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Crispy breaded fish strips, kids favorite.',
        tags: ['Breaded', 'Strips', 'Kids favorite', 'Crispy'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),
      Recipe(
        id: '94',
        name: 'Chicken Shawarma',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Middle Eastern inspired chicken wrap.',
        tags: ['Middle Eastern', 'Wrap', 'Inspired', 'Marinated'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),
      Recipe(
        id: '95',
        name: 'Beef Kebab',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Spiced beef kebabs grilled to perfection.',
        tags: ['Spiced', 'Grilled', 'Perfection', 'BBQ'],
        imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
      ),
      Recipe(
        id: '96',
        name: 'Chicken Yakhni',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Light chicken broth with minimal spices.',
        tags: ['Light', 'Broth', 'Minimal spices', 'Healthy'],
        imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
      ),
      Recipe(
        id: '97',
        name: 'Mixed Vegetable Curry',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Seasonal mixed vegetables in curry sauce.',
        tags: ['Seasonal', 'Mixed', 'Curry sauce', 'Healthy'],
        imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400',
      ),
      Recipe(
        id: '98',
        name: 'Chicken Malai Boti',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Creamy marinated chicken pieces, mild and rich.',
        tags: ['Creamy', 'Marinated', 'Mild', 'Rich'],
        imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
      ),
      Recipe(
        id: '99',
        name: 'Beef Stir Fry',
        type: 'Mutton/Beef',
        time: '30-35 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Quick beef stir fry with vegetables.',
        tags: ['Quick', 'Stir fry', 'Vegetables', 'Fast'],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
      ),
      Recipe(
        id: '100',
        name: 'Prawn Biryani',
        type: 'Fish/SeaFood',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Aromatic biryani with fresh prawns and spices.',
        tags: ['Prawns', 'Aromatic', 'Fresh', 'Spices'],
        imageUrl: 'https://images.unsplash.com/photo-1563379091339-03246963d51a?w=400',
      ),
      Recipe(
        id: '101',
        name: 'Chicken Drumsticks',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Marinated and grilled chicken drumsticks.',
        tags: ['Drumsticks', 'Marinated', 'Grilled', 'Juicy'],
        imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
      ),
      Recipe(
        id: '102',
        name: 'Vegetable Soup',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Healthy mixed vegetable soup, perfect for cold weather.',
        tags: ['Healthy', 'Mixed vegetables', 'Soup', 'Warm'],
        imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
      ),
      Recipe(
        id: '103',
        name: 'Mutton Ribs',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Slow-cooked mutton ribs with aromatic spices.',
        tags: ['Ribs', 'Slow-cooked', 'Aromatic', 'Tender'],
        imageUrl: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400',
      ),
      Recipe(
        id: '104',
        name: 'Chicken Caesar Salad',
        type: 'Chicken',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Fresh chicken salad with caesar dressing.',
        tags: ['Salad', 'Fresh', 'Caesar', 'Light'],
        imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400',
      ),
      Recipe(
        id: '105',
        name: 'Fish Karahi',
        type: 'Fish/SeaFood',
        time: '30-35 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Fish cooked in traditional karahi style with tomatoes.',
        tags: ['Fish', 'Karahi', 'Tomatoes', 'Traditional'],
        imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
      ),
    ];
  }
}