
import 'main.dart';

class RecipeData {
  static List<Recipe> getAllRecipesData() {
    return [
      // CHICKEN DISHES
      Recipe(
        id: '1',
        name: 'Chicken Karahi',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Traditional chicken karahi with tomatoes, ginger, and aromatic spices.',
        tags: ['Chicken', 'Karahi', 'Tomatoes', 'Ginger', 'Spices'],
        imageUrl: '',
      ),
      Recipe(
        id: '2',
        name: 'Chicken Biryani',
        type: 'Chicken',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Fragrant basmati rice layered with spiced chicken pieces and saffron.',
        tags: ['Chicken', 'Rice', 'Biryani', 'Saffron', 'Festive'],
        imageUrl: '',
      ),
      Recipe(
        id: '3',
        name: 'Chicken Pulao',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple one-pot chicken and rice dish, perfect for rainy days.',
        tags: ['Chicken', 'Rice', 'One-pot', 'Comfort', 'Simple'],
        imageUrl: '',
      ),
      Recipe(
        id: '4',
        name: 'Chicken Qorma',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Rich and creamy chicken curry with yogurt, onions, and aromatic spices.',
        tags: ['Chicken', 'Creamy', 'Yogurt', 'Rich', 'Onions'],
        imageUrl: '',
      ),
      Recipe(
        id: '5',
        name: 'Chicken Shorba',
        type: 'Chicken',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Light and healthy chicken soup with vegetables, perfect for cold weather.',
        tags: ['Chicken', 'Soup', 'Healthy', 'Light', 'Vegetables'],
        imageUrl: '',
      ),
      Recipe(
        id: '6',
        name: 'Chicken Tikka',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Marinated chicken pieces grilled to perfection with traditional spices.',
        tags: ['Chicken', 'Grilled', 'Marinated', 'BBQ', 'Spices'],
        imageUrl: '',
      ),
      Recipe(
        id: '7',
        name: 'Chicken Keema',
        type: 'Chicken',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced minced chicken curry with peas, quick and flavorful.',
        tags: ['Chicken', 'Minced', 'Quick', 'Spicy', 'Peas'],
        imageUrl: '',
      ),
      Recipe(
        id: '8',
        name: 'Chicken Pakora',
        type: 'Chicken',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Crispy chicken fritters with gram flour, perfect rainy day snack.',
        tags: ['Chicken', 'Fritters', 'Snack', 'Crispy', 'Gram flour'],
        imageUrl: '',
      ),

      // MUTTON/BEEF DISHES
      Recipe(
        id: '9',
        name: 'Aloo Gosht',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Traditional mutton/beef curry with potatoes, rich and hearty.',
        tags: ['Mutton', 'Beef', 'Potatoes', 'Curry', 'Hearty'],
        imageUrl: '',
      ),
      Recipe(
        id: '10',
        name: 'Mutton Biryani',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Royal mutton biryani with aromatic spices, saffron, and mint.',
        tags: ['Mutton', 'Rice', 'Biryani', 'Royal', 'Saffron'],
        imageUrl: '',
      ),
      Recipe(
        id: '11',
        name: 'Mutton Karahi',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Traditional mutton cooked in karahi with tomatoes and ginger.',
        tags: ['Mutton', 'Karahi', 'Traditional', 'Spicy', 'Tomatoes'],
        imageUrl: '',
      ),
      Recipe(
        id: '12',
        name: 'Beef Nihari',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Slow-cooked beef stew with wheat flour, perfect for cold mornings.',
        tags: ['Beef', 'Slow-cooked', 'Rich', 'Traditional', 'Wheat flour'],
        imageUrl: '',
      ),
      Recipe(
        id: '13',
        name: 'Beef Qeema',
        type: 'Mutton/Beef',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced minced beef curry with peas, quick and satisfying.',
        tags: ['Beef', 'Minced', 'Quick', 'Spiced', 'Peas'],
        imageUrl: '',
      ),
      Recipe(
        id: '14',
        name: 'Mutton Yakhni Pulao',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Low energy',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Fragrant rice cooked in mutton broth with whole spices.',
        tags: ['Mutton', 'Rice', 'Broth', 'Aromatic', 'Whole spices'],
        imageUrl: '',
      ),
      Recipe(
        id: '15',
        name: 'Beef Paya',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Traditional slow-cooked beef trotters, winter special.',
        tags: ['Beef', 'Trotters', 'Slow-cooked', 'Traditional', 'Winter'],
        imageUrl: '',
      ),
      Recipe(
        id: '16',
        name: 'Seekh Kabab',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Grilled minced meat skewers with aromatic spices and herbs.',
        tags: ['Kabab', 'Grilled', 'Minced', 'Skewers', 'Herbs'],
        imageUrl: '',
      ),

      // VEGETABLE DISHES
      Recipe(
        id: '17',
        name: 'Aloo Palak',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Nutritious potato and spinach curry with traditional spices.',
        tags: ['Potato', 'Spinach', 'Healthy', 'Vegetarian', 'Spices'],
        imageUrl: '',
      ),
      Recipe(
        id: '18',
        name: 'Aloo Matar',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple potato and peas curry, comfort food at its best.',
        tags: ['Potato', 'Peas', 'Simple', 'Comfort', 'Quick'],
        imageUrl: '',
      ),
      Recipe(
        id: '19',
        name: 'Aloo Gobi',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Traditional potato and cauliflower curry with turmeric and cumin.',
        tags: ['Potato', 'Cauliflower', 'Traditional', 'Turmeric', 'Cumin'],
        imageUrl: '',
      ),
      Recipe(
        id: '20',
        name: 'Bhindi Masala',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced okra curry with onions and tomatoes, perfect for hot weather.',
        tags: ['Okra', 'Spices', 'Quick', 'Summer', 'Onions'],
        imageUrl: '',
      ),
      Recipe(
        id: '21',
        name: 'Mixed Sabzi',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Healthy mix of seasonal vegetables with light spices.',
        tags: ['Mixed', 'Healthy', 'Seasonal', 'Light', 'Quick'],
        imageUrl: '',
      ),
      Recipe(
        id: '22',
        name: 'Baingan Bharta',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Roasted eggplant curry with onions, tomatoes, and spices.',
        tags: ['Eggplant', 'Roasted', 'Curry', 'Onions', 'Tomatoes'],
        imageUrl: '',
      ),
      Recipe(
        id: '23',
        name: 'Gajar Ka Halwa',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Traditional carrot pudding with milk, sugar, and cardamom.',
        tags: ['Carrots', 'Dessert', 'Milk', 'Cardamom', 'Sweet'],
        imageUrl: '',
      ),

      // LENTILS DISHES
      Recipe(
        id: '24',
        name: 'Daal Chawal',
        type: 'Lentils',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple yellow lentils with rice, ultimate comfort food.',
        tags: ['Lentils', 'Rice', 'Comfort', 'Simple', 'Yellow daal'],
        imageUrl: '',
      ),
      Recipe(
        id: '25',
        name: 'Chana Daal',
        type: 'Lentils',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Nutritious split chickpea curry with traditional spices.',
        tags: ['Chickpeas', 'Nutritious', 'Protein', 'Healthy', 'Split'],
        imageUrl: '',
      ),
      Recipe(
        id: '26',
        name: 'Masoor Daal',
        type: 'Lentils',
        time: '20-25 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Red lentils cooked with onions, tomatoes, and basic spices.',
        tags: ['Red lentils', 'Quick', 'Simple', 'Onions', 'Tomatoes'],
        imageUrl: '',
      ),
      Recipe(
        id: '27',
        name: 'Moong Daal',
        type: 'Lentils',
        time: '20-25 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Light yellow mung beans, perfect for hot weather.',
        tags: ['Mung beans', 'Light', 'Summer', 'Quick', 'Simple'],
        imageUrl: '',
      ),
      Recipe(
        id: '28',
        name: 'Urad Daal',
        type: 'Lentils',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Black gram lentils with rich spices, winter comfort food.',
        tags: ['Black gram', 'Rich', 'Winter', 'Comfort', 'Spices'],
        imageUrl: '',
      ),

      // RICE DISHES
      Recipe(
        id: '29',
        name: 'Plain Rice',
        type: 'Rice',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple steamed basmati rice, perfect with any curry.',
        tags: ['Rice', 'Basmati', 'Simple', 'Steamed', 'Basic'],
        imageUrl: '',
      ),
      Recipe(
        id: '30',
        name: 'Zeera Rice',
        type: 'Rice',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Cumin-flavored rice with whole spices and ghee.',
        tags: ['Rice', 'Cumin', 'Whole spices', 'Ghee', 'Aromatic'],
        imageUrl: '',
      ),
      Recipe(
        id: '31',
        name: 'Matar Pulao',
        type: 'Rice',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Peas pulao with whole spices and aromatic rice.',
        tags: ['Rice', 'Peas', 'Whole spices', 'Aromatic', 'Simple'],
        imageUrl: '',
      ),
      Recipe(
        id: '32',
        name: 'Khichdi',
        type: 'Rice',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Comfort food made with rice and lentils, perfect for rainy days.',
        tags: ['Rice', 'Lentils', 'Comfort', 'Rainy-day', 'One-pot'],
        imageUrl: '',
      ),
      Recipe(
        id: '33',
        name: 'Tahari',
        type: 'Rice',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Rice cooked with meat and vegetables, hearty one-pot meal.',
        tags: ['Rice', 'Meat', 'Vegetables', 'One-pot', 'Hearty'],
        imageUrl: '',
      ),
      Recipe(
        id: '34',
        name: 'Kashmiri Pulao',
        type: 'Rice',
        time: '45 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Colorful rice with dried fruits, nuts, and mild spices.',
        tags: ['Rice', 'Dried fruits', 'Nuts', 'Colorful', 'Festive'],
        imageUrl: '',
      ),
      Recipe(
        id: '35',
        name: 'Sada Chawal',
        type: 'Rice',
        time: '25-30 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple white rice, everyday staple food.',
        tags: ['Rice', 'White', 'Staple', 'Simple', 'Everyday'],
        imageUrl: '',
      ),

      // ADDITIONAL CHICKEN DISHES
      Recipe(
        id: '36',
        name: 'Chicken Do Pyaza',
        type: 'Chicken',
        time: '45 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Chicken curry with double onions, rich and flavorful.',
        tags: ['Chicken', 'Onions', 'Curry', 'Rich', 'Traditional'],
        imageUrl: '',
      ),
      Recipe(
        id: '37',
        name: 'Chicken Jalfrezi',
        type: 'Chicken',
        time: '40 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Spicy chicken with bell peppers and onions.',
        tags: ['Chicken', 'Bell peppers', 'Spicy', 'Quick', 'Colorful'],
        imageUrl: '',
      ),
      Recipe(
        id: '38',
        name: 'Chicken Handi',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Creamy chicken curry cooked in traditional handi pot.',
        tags: ['Chicken', 'Handi', 'Creamy', 'Traditional', 'Rich'],
        imageUrl: '',
      ),
      Recipe(
        id: '39',
        name: 'Chicken Masala',
        type: 'Chicken',
        time: '45 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Classic chicken curry with aromatic masala spices.',
        tags: ['Chicken', 'Masala', 'Classic', 'Aromatic', 'Spices'],
        imageUrl: '',
      ),
      Recipe(
        id: '40',
        name: 'Chicken Bhuna',
        type: 'Chicken',
        time: '50 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Dry-style chicken curry with thick masala gravy.',
        tags: ['Chicken', 'Bhuna', 'Dry', 'Thick gravy', 'Spicy'],
        imageUrl: '',
      ),

      // ADDITIONAL MUTTON/BEEF DISHES
      Recipe(
        id: '41',
        name: 'Beef Bhuna',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Dry-style beef curry with rich masala coating.',
        tags: ['Beef', 'Bhuna', 'Dry', 'Rich', 'Masala'],
        imageUrl: '',
      ),
      Recipe(
        id: '42',
        name: 'Mutton Do Pyaza',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Mutton curry with double onions and aromatic spices.',
        tags: ['Mutton', 'Onions', 'Curry', 'Aromatic', 'Traditional'],
        imageUrl: '',
      ),
      Recipe(
        id: '43',
        name: 'Beef Masala',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Classic beef curry with traditional masala blend.',
        tags: ['Beef', 'Masala', 'Classic', 'Traditional', 'Curry'],
        imageUrl: '',
      ),
      Recipe(
        id: '44',
        name: 'Mutton Bhuna',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Dry-style mutton curry with thick masala gravy.',
        tags: ['Mutton', 'Bhuna', 'Dry', 'Thick gravy', 'Spicy'],
        imageUrl: '',
      ),
      Recipe(
        id: '45',
        name: 'Beef Yakhni Pulao',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Low energy',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Fragrant rice cooked in beef broth with whole spices.',
        tags: ['Beef', 'Rice', 'Broth', 'Aromatic', 'Whole spices'],
        imageUrl: '',
      ),

      // ADDITIONAL VEGETABLE DISHES
      Recipe(
        id: '46',
        name: 'Aloo Bhujia',
        type: 'Vegetables',
        time: '20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spicy potato stir-fry with onions and spices.',
        tags: ['Potato', 'Stir-fry', 'Spicy', 'Quick', 'Onions'],
        imageUrl: '',
      ),
      Recipe(
        id: '47',
        name: 'Gobhi Aloo',
        type: 'Vegetables',
        time: '25 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Cauliflower and potato curry with turmeric.',
        tags: ['Cauliflower', 'Potato', 'Turmeric', 'Simple', 'Quick'],
        imageUrl: '',
      ),
      Recipe(
        id: '48',
        name: 'Baingan Ka Bharta',
        type: 'Vegetables',
        time: '30 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Roasted eggplant mash with onions and tomatoes.',
        tags: ['Eggplant', 'Roasted', 'Mash', 'Onions', 'Tomatoes'],
        imageUrl: '',
      ),
      Recipe(
        id: '49',
        name: 'Karela Masala',
        type: 'Vegetables',
        time: '25 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Bitter gourd curry with spices and onions.',
        tags: ['Bitter gourd', 'Spices', 'Onions', 'Traditional', 'Healthy'],
        imageUrl: '',
      ),
      Recipe(
        id: '50',
        name: 'Tinda Masala',
        type: 'Vegetables',
        time: '20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Apple gourd curry with light spices.',
        tags: ['Apple gourd', 'Light', 'Mild', 'Quick', 'Simple'],
        imageUrl: '',
      ),

      // ADDITIONAL LENTILS DISHES
      Recipe(
        id: '51',
        name: 'Arhar Daal',
        type: 'Lentils',
        time: '25 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Pigeon pea lentils with basic spices.',
        tags: ['Pigeon peas', 'Basic', 'Quick', 'Simple', 'Traditional'],
        imageUrl: '',
      ),
      Recipe(
        id: '52',
        name: 'Mash Daal',
        type: 'Lentils',
        time: '30 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Black gram lentils with rich spices, winter comfort.',
        tags: ['Black gram', 'Rich', 'Winter', 'Comfort', 'Spices'],
        imageUrl: '',
      ),
      Recipe(
        id: '53',
        name: 'Lobia Daal',
        type: 'Lentils',
        time: '35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Black-eyed peas with traditional spices.',
        tags: ['Black-eyed peas', 'Traditional', 'Spices', 'Protein', 'Healthy'],
        imageUrl: '',
      ),
      Recipe(
        id: '54',
        name: 'Rajma Daal',
        type: 'Lentils',
        time: '40 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Kidney beans curry with rich masala.',
        tags: ['Kidney beans', 'Rich', 'Masala', 'Winter', 'Protein'],
        imageUrl: '',
      ),
      Recipe(
        id: '55',
        name: 'Safed Daal',
        type: 'Lentils',
        time: '25 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'White lentils with light spices and ghee.',
        tags: ['White lentils', 'Light', 'Ghee', 'Simple', 'Quick'],
        imageUrl: '',
      ),

      // ADDITIONAL RICE DISHES
      Recipe(
        id: '56',
        name: 'Meetha Chawal',
        type: 'Rice',
        time: '30 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Sweet rice with sugar, cardamom, and nuts.',
        tags: ['Rice', 'Sweet', 'Sugar', 'Cardamom', 'Nuts'],
        imageUrl: '',
      ),
      Recipe(
        id: '57',
        name: 'Pulao Gosht',
        type: 'Rice',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Rice cooked with meat and whole spices.',
        tags: ['Rice', 'Meat', 'Whole spices', 'Aromatic', 'Hearty'],
        imageUrl: '',
      ),
      Recipe(
        id: '58',
        name: 'Yakhni Pulao',
        type: 'Rice',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Rice cooked in meat broth with whole spices.',
        tags: ['Rice', 'Broth', 'Whole spices', 'Aromatic', 'Simple'],
        imageUrl: '',
      ),
      Recipe(
        id: '59',
        name: 'Nawabi Pulao',
        type: 'Rice',
        time: '45 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Royal rice with dried fruits and nuts.',
        tags: ['Rice', 'Royal', 'Dried fruits', 'Nuts', 'Festive'],
        imageUrl: '',
      ),
      Recipe(
        id: '60',
        name: 'Sada Pulao',
        type: 'Rice',
        time: '30 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple rice with basic spices and ghee.',
        tags: ['Rice', 'Simple', 'Basic', 'Ghee', 'Everyday'],
        imageUrl: '',
      ),
    ];
  }
}