
import 'main.dart';

class RecipeData {
  static List<Recipe> getAllRecipesData() {
    return [
      // DAILY CHICKEN DISHES
      Recipe(
        id: '1',
        name: 'Chicken Curry',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Ghar ka masala chicken curry with onions and tomatoes.',
        tags: ['Chicken', 'Daily', 'Masala', 'Home-style'],
        imageUrl: 'https://www.licious.in/blog/wp-content/uploads/2020/12/chicken-curry.jpg',
      ),
      Recipe(
        id: '2',
        name: 'Chicken Karahi',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Traditional chicken karahi with fresh tomatoes and green chilies.',
        tags: ['Chicken', 'Karahi', 'Tomatoes', 'Traditional'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2019/04/Chicken-Karahi-Recipe.jpg',
      ),
      Recipe(
        id: '3',
        name: 'Chicken Biryani',
        type: 'Chicken',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Aromatic chicken biryani with basmati rice and saffron.',
        tags: ['Chicken', 'Rice', 'Biryani', 'Special'],
        imageUrl: 'https://www.cookwithmanali.com/wp-content/uploads/2019/04/Chicken-Biryani-Recipe.jpg',
      ),
      Recipe(
        id: '4',
        name: 'Chicken Pulao',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'One-pot chicken pulao, perfect for daily meals.',
        tags: ['Chicken', 'Rice', 'One-pot', 'Easy'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/09/Chicken-Pulao.jpg',
      ),
      Recipe(
        id: '5',
        name: 'Chicken Keema',
        type: 'Chicken',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Minced chicken cooked with onions and spices.',
        tags: ['Chicken', 'Keema', 'Quick', 'Daily'],
        imageUrl: 'https://www.pakistanihealthyrecipes.com/wp-content/uploads/2017/05/Chicken-Keema-Recipe.jpg',
      ),

      // MUTTON/BEEF DISHES
      Recipe(
        id: '6',
        name: 'Mutton Curry',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Slow-cooked mutton curry with traditional spices.',
        tags: ['Mutton', 'Curry', 'Traditional', 'Rich'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/08/Mutton-Curry.jpg',
      ),
      Recipe(
        id: '7',
        name: 'Beef Qeema',
        type: 'Mutton/Beef',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced minced beef, quick and tasty.',
        tags: ['Beef', 'Qeema', 'Quick', 'Spiced'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/12/Beef-Qeema.jpg',
      ),
      Recipe(
        id: '8',
        name: 'Mutton Karahi',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Traditional mutton karahi with fresh ginger.',
        tags: ['Mutton', 'Karahi', 'Ginger', 'Hot'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2019/02/Mutton-Karahi.jpg',
      ),

      // DAILY VEGETABLE DISHES
      Recipe(
        id: '9',
        name: 'Aloo Gobi',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Potato and cauliflower curry, everyday favorite.',
        tags: ['Potato', 'Cauliflower', 'Daily', 'Simple'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/05/Aloo-Gobi.jpg',
      ),
      Recipe(
        id: '10',
        name: 'Aloo Palak',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Potato and spinach curry, healthy and tasty.',
        tags: ['Potato', 'Spinach', 'Healthy', 'Daily'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/03/Aloo-Palak.jpg',
      ),
      Recipe(
        id: '11',
        name: 'Bhindi Masala',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Okra cooked with onions and spices.',
        tags: ['Okra', 'Masala', 'Summer', 'Healthy'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/07/Bhindi-Masala.jpg',
      ),
      Recipe(
        id: '12',
        name: 'Aloo Matar',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Potato and peas curry, comfort food.',
        tags: ['Potato', 'Peas', 'Comfort', 'Easy'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/04/Aloo-Matar.jpg',
      ),
      Recipe(
        id: '13',
        name: 'Baingan Bhartha',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Roasted eggplant mash with spices.',
        tags: ['Eggplant', 'Roasted', 'Summer', 'Traditional'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/06/Baingan-Bhartha.jpg',
      ),
      Recipe(
        id: '14',
        name: 'Karela Masala',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Bitter gourd curry, healthy summer dish.',
        tags: ['Karela', 'Healthy', 'Summer', 'Bitter'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/08/Karela-Masala.jpg',
      ),
      Recipe(
        id: '15',
        name: 'Tinda Masala',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Round gourd curry, summer vegetable.',
        tags: ['Tinda', 'Summer', 'Gourd', 'Light'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2019/05/Tinda-Masala.jpg',
      ),

      // LENTILS - DAILY STAPLES
      Recipe(
        id: '16',
        name: 'Dal Chawal',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple lentils with rice, ultimate comfort food.',
        tags: ['Dal', 'Rice', 'Daily', 'Comfort'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/11/Dal-Chawal.jpg',
      ),
      Recipe(
        id: '17',
        name: 'Chana Dal',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Split chickpea lentils, protein-rich daily meal.',
        tags: ['Chana Dal', 'Protein', 'Daily', 'Healthy'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/01/Chana-Dal.jpg',
      ),
      Recipe(
        id: '18',
        name: 'Masoor Dal',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Red lentils, quick cooking and nutritious.',
        tags: ['Masoor', 'Quick', 'Red lentils', 'Easy'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/09/Masoor-Dal.jpg',
      ),
      Recipe(
        id: '19',
        name: 'Moong Dal',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Yellow lentils, light and easy to digest.',
        tags: ['Moong', 'Light', 'Digestible', 'Summer'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/10/Moong-Dal.jpg',
      ),
      Recipe(
        id: '20',
        name: 'Mixed Dal',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Combination of different lentils, nutritious.',
        tags: ['Mixed', 'Lentils', 'Nutritious', 'Daily'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/02/Mixed-Dal.jpg',
      ),

      // EGG DISHES - QUICK MEALS
      Recipe(
        id: '21',
        name: 'Anda Curry',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Egg curry, quick and protein-rich meal.',
        tags: ['Eggs', 'Quick', 'Protein', 'Easy'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/08/Anda-Curry.jpg',
      ),
      Recipe(
        id: '22',
        name: 'Anda Paratha',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Egg-stuffed paratha, perfect breakfast.',
        tags: ['Eggs', 'Paratha', 'Breakfast', 'Stuffed'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/11/Anda-Paratha.jpg',
      ),
      Recipe(
        id: '23',
        name: 'Bhurji',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Scrambled eggs with onions and spices.',
        tags: ['Eggs', 'Scrambled', 'Quick', 'Breakfast'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/07/Bhurji.jpg',
      ),

      // BREAD/ROTI - DAILY STAPLES
      Recipe(
        id: '24',
        name: 'Roti',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Fresh wheat flatbread, daily staple.',
        tags: ['Roti', 'Wheat', 'Daily', 'Bread'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/06/Roti.jpg',
      ),
      Recipe(
        id: '25',
        name: 'Paratha',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Layered flatbread with ghee.',
        tags: ['Paratha', 'Layered', 'Ghee', 'Breakfast'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/12/Paratha.jpg',
      ),
      Recipe(
        id: '26',
        name: 'Aloo Paratha',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Potato-stuffed paratha, hearty breakfast.',
        tags: ['Potato', 'Paratha', 'Stuffed', 'Breakfast'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/10/Aloo-Paratha.jpg',
      ),

      // RICE DISHES
      Recipe(
        id: '27',
        name: 'Plain Rice',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple steamed basmati rice.',
        tags: ['Rice', 'Plain', 'Simple', 'Daily'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/05/Plain-Rice.jpg',
      ),
      Recipe(
        id: '28',
        name: 'Zeera Rice',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Cumin-flavored basmati rice.',
        tags: ['Rice', 'Cumin', 'Aromatic', 'Simple'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/12/Zeera-Rice.jpg',
      ),
      Recipe(
        id: '29',
        name: 'Vegetable Pulao',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Mixed vegetable rice, one-pot meal.',
        tags: ['Vegetables', 'Rice', 'One-pot', 'Healthy'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/09/Vegetable-Pulao.jpg',
      ),

      // RAINY DAY SPECIALS
      Recipe(
        id: '30',
        name: 'Pakoray',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Mixed vegetable fritters, perfect for rain.',
        tags: ['Fritters', 'Rainy', 'Crispy', 'Tea-time'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/07/Pakoray.jpg',
      ),
      Recipe(
        id: '31',
        name: 'Samosa',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Active',
        budget: 'Low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Crispy triangular pastries with potato filling.',
        tags: ['Samosa', 'Crispy', 'Potato', 'Tea-time'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2019/01/Samosa.jpg',
      ),
      Recipe(
        id: '32',
        name: 'Khichdi',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Rice and lentil porridge, comfort food.',
        tags: ['Rice', 'Lentils', 'Comfort', 'Sick-food'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/11/Khichdi.jpg',
      ),

      // WINTER SPECIALS
      Recipe(
        id: '33',
        name: 'Saag',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Mixed greens curry, winter specialty.',
        tags: ['Greens', 'Winter', 'Healthy', 'Traditional'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/01/Saag.jpg',
      ),
      Recipe(
        id: '34',
        name: 'Gajar Matar',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Carrot and peas curry, winter vegetables.',
        tags: ['Carrot', 'Peas', 'Winter', 'Sweet'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2019/01/Gajar-Matar.jpg',
      ),
      Recipe(
        id: '35',
        name: 'Shaljam Gajar',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Turnip and carrot curry, winter comfort.',
        tags: ['Turnip', 'Carrot', 'Winter', 'Root vegetables'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/12/Shaljam-Gajar.jpg',
      ),

      // FISH DISHES
      Recipe(
        id: '36',
        name: 'Fish Curry',
        type: 'Fish/SeaFood',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Traditional fish curry with spices.',
        tags: ['Fish', 'Curry', 'Traditional', 'Protein'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/03/Fish-Curry.jpg',
      ),
      Recipe(
        id: '37',
        name: 'Fried Fish',
        type: 'Fish/SeaFood',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Crispy fried fish with masala.',
        tags: ['Fish', 'Fried', 'Crispy', 'Masala'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/05/Fried-Fish.jpg',
      ),

      // QUICK BREAKFAST ITEMS
      Recipe(
        id: '38',
        name: 'Halwa Puri',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Traditional breakfast with semolina halwa.',
        tags: ['Breakfast', 'Traditional', 'Halwa', 'Puri'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2019/03/Halwa-Puri.jpg',
      ),
      Recipe(
        id: '39',
        name: 'Channay',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Spiced chickpeas, breakfast staple.',
        tags: ['Chickpeas', 'Breakfast', 'Protein', 'Traditional'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/04/Channay.jpg',
      ),
      Recipe(
        id: '40',
        name: 'Nihari',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Slow-cooked beef stew, weekend special.',
        tags: ['Beef', 'Slow-cooked', 'Rich', 'Weekend'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/02/Nihari.jpg',
      ),

      // MORE DAILY VEGETABLES
      Recipe(
        id: '41',
        name: 'Arvi Masala',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Taro root curry, traditional vegetable.',
        tags: ['Arvi', 'Root vegetable', 'Traditional', 'Spiced'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/09/Arvi-Masala.jpg',
      ),
      Recipe(
        id: '42',
        name: 'Lauki Sabzi',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Bottle gourd curry, light summer dish.',
        tags: ['Lauki', 'Light', 'Summer', 'Healthy'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/06/Lauki-Sabzi.jpg',
      ),
      Recipe(
        id: '43',
        name: 'Cabbage Sabzi',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Simple cabbage stir-fry, quick and healthy.',
        tags: ['Cabbage', 'Quick', 'Healthy', 'Stir-fry'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/09/Cabbage-Sabzi.jpg',
      ),
      Recipe(
        id: '44',
        name: 'Shimla Mirch',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Bell pepper stir-fry, colorful and tasty.',
        tags: ['Bell pepper', 'Colorful', 'Quick', 'Light'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/07/Shimla-Mirch.jpg',
      ),
      Recipe(
        id: '45',
        name: 'Dahi Baingan',
        type: 'Vegetables',
        time: '30-35 minutes',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Eggplant in yogurt gravy, cooling dish.',
        tags: ['Eggplant', 'Yogurt', 'Cooling', 'Summer'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/08/Dahi-Baingan.jpg',
      ),

      // MORE CHICKEN VARIETIES
      Recipe(
        id: '46',
        name: 'Chicken Tikka',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Grilled chicken pieces with yogurt marinade.',
        tags: ['Chicken', 'Grilled', 'Tikka', 'Marinated'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/11/Chicken-Tikka.jpg',
      ),
      Recipe(
        id: '47',
        name: 'Chicken Jalfrezi',
        type: 'Chicken',
        time: '30-35 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Chicken stir-fry with colorful vegetables.',
        tags: ['Chicken', 'Stir-fry', 'Vegetables', 'Colorful'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/09/Chicken-Jalfrezi.jpg',
      ),
      Recipe(
        id: '48',
        name: 'Chicken Qorma',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'High budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Rich chicken curry with yogurt and cream.',
        tags: ['Chicken', 'Rich', 'Creamy', 'Special'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/01/Chicken-Qorma.jpg',
      ),

      // RAITA & SIDES
      Recipe(
        id: '49',
        name: 'Raita',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Yogurt side dish with cucumber and mint.',
        tags: ['Yogurt', 'Side dish', 'Cooling', 'Fresh'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/08/Raita.jpg',
      ),
      Recipe(
        id: '50',
        name: 'Kachumber Salad',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Fresh cucumber tomato salad, summer favorite.',
        tags: ['Salad', 'Fresh', 'Summer', 'Raw'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/07/Kachumber-Salad.jpg',
      ),

      // SPECIAL OCCASION DISHES
      Recipe(
        id: '51',
        name: 'Haleem',
        type: 'Mutton/Beef',
        time: 'No worry of time',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Cold',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Lentil and meat stew, Ramadan special.',
        tags: ['Lentils', 'Meat', 'Ramadan', 'Rich'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/05/Haleem.jpg',
      ),
      Recipe(
        id: '52',
        name: 'Seekh Kebab',
        type: 'Mutton/Beef',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Grilled minced meat skewers.',
        tags: ['Kebab', 'Grilled', 'Minced', 'BBQ'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/04/Seekh-Kebab.jpg',
      ),
      Recipe(
        id: '53',
        name: 'Chapli Kebab',
        type: 'Mutton/Beef',
        time: '30-35 minutes',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Hot',
        description: 'Flat meat patties, Peshawari specialty.',
        tags: ['Kebab', 'Flat', 'Peshawari', 'Spicy'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2019/02/Chapli-Kebab.jpg',
      ),

      // MORE DAILY ESSENTIALS
      Recipe(
        id: '54',
        name: 'Keema Paratha',
        type: 'Chicken',
        time: '1 hour',
        energy: 'Active',
        budget: 'Medium budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Medium',
        description: 'Minced meat stuffed paratha.',
        tags: ['Keema', 'Paratha', 'Stuffed', 'Protein'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/12/Keema-Paratha.jpg',
      ),
      Recipe(
        id: '55',
        name: 'Karhi Pakora',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Low energy',
        budget: 'Low budget',
        weather: 'Rainy',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Yogurt curry with gram flour fritters.',
        tags: ['Yogurt', 'Curry', 'Pakora', 'Rainy'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/08/Karhi-Pakora.jpg',
      ),

      // TEA TIME SNACKS
      Recipe(
        id: '56',
        name: 'Chai',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Traditional milk tea with cardamom.',
        tags: ['Tea', 'Milk', 'Cardamom', 'Daily'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/06/Chai.jpg',
      ),
      Recipe(
        id: '57',
        name: 'Namak Para',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Active',
        budget: 'Low budget',
        weather: 'Normal',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Crispy savory crackers for tea time.',
        tags: ['Snack', 'Crispy', 'Tea-time', 'Savory'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/10/Namak-Para.jpg',
      ),

      // SUMMER COOLING DISHES
      Recipe(
        id: '58',
        name: 'Lassi',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Very low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Refreshing yogurt drink for summer.',
        tags: ['Yogurt', 'Drink', 'Summer', 'Refreshing'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/05/Lassi.jpg',
      ),
      Recipe(
        id: '59',
        name: 'Dahi Bhalla',
        type: 'Vegetables',
        time: '1 hour',
        energy: 'Active',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Lentil dumplings in yogurt, cooling dish.',
        tags: ['Lentils', 'Yogurt', 'Cooling', 'Traditional'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2018/06/Dahi-Bhalla.jpg',
      ),
      Recipe(
        id: '60',
        name: 'Fruit Chaat',
        type: 'Vegetables',
        time: '15-20 minutes',
        energy: 'Very low energy',
        budget: 'Low budget',
        weather: 'Hot',
        cuisine: 'Pakistani',
        spiceLevel: 'Mild',
        description: 'Mixed fruit salad with chaat masala.',
        tags: ['Fruits', 'Healthy', 'Fresh', 'Summer'],
        imageUrl: 'https://www.masala.tv/wp-content/uploads/2017/04/Fruit-Chaat.jpg',
      ),
    ];
  }
}